### ISSUE TITLE
custom-initialize-reset: Symbol’s value as variable is void: eglot-server-programs

### ISSUE THREAD

**Issue by CsBigDataHub** [jdtsmith/eglot-booster#1]
config added to my `.emacs` file  -

```emacs-lisp
(use-package eglot-booster
       :after eglot
       :straight
       (eglot-booster
        :type git
        :host github
        :repo "jdtsmith/eglot-booster")
       :config (eglot-booster-mode))
```

error at start up -

`custom-initialize-reset: Symbol’s value as variable is void: eglot-server-programs`

Is it a right approach to activate `eglot-booster-mode` with `eglot-managed-mode-hook` ?

**Comment by jdtsmith** [comment]
This shouldn't happen.  What happens if you `M-x package-vc-install` and remove the straight stuff?

**Comment by CsBigDataHub** [comment]
@jdtsmith Thanks, no sure what happened. Deleting `straight` directory and restarting emacs worked.
