### ISSUE TITLE
option to disable translation of JSON to Elisp bytecode

### ISSUE THREAD

**Issue by maxecharel** [jdtsmith/eglot-booster#12]
Hi @jdtsmith,

To let the new JSON parser introduced in Emacs 30 do its job, would be nice to have an option to run `emacs-lsp-booster` via `eglot-booster` with the `--disable-bytecode` flag (see https://github.com/blahgeek/emacs-lsp-booster/issues/25). Would you be willing to implement such feature?

If you have no time and would like me to give a shot at it, please tell me.

Thanks a lot for the great work!

**Comment by maxecharel** [comment]
Nice, thanks for the feature! `*EGLOT events*` seems to indicate that it works:
```
[stderr]  [2024-10-29T22:22:55Z INFO  emacs_lsp_booster::app] Running server "/snap/bin/pyright-langserver" "--stdio"
[stderr]  [2024-10-29T22:22:55Z INFO  emacs_lsp_booster::app] Bytecode disabled! Will forward server json as-is.
```
However, I do not understand why the log mentions the error stream at the beginning of each entry. Haven't realized that before; any idea?

**Comment by jdtsmith** [comment]
I think eglot just logs stderr.

**Comment by maxecharel** [comment]
The event buffer (that `M-x eglot-events-buffer` pops up) and the debug info buffer (that `M-x eglot-stderr-buffer` pops up and that displays the stderr stream of the language server) are two different things, but it seems that the former also shows what ends up in the latter. In the event buffer:
```
[stderr]  [(...) INFO  emacs_lsp_booster::app] Running server "/snap/bin/pyright-langserver" "--stdio"
[stderr]  [(...) INFO  emacs_lsp_booster::app] Bytecode disabled! Will forward server json as-is.
```
In the debug info buffer:
```
[(...) INFO  emacs_lsp_booster::app] Running server "/snap/bin/pyright-langserver" "--stdio"
[(...) INFO  emacs_lsp_booster::app] Bytecode disabled! Will forward server json as-is.
```
What actually surprises me is that AFAIU `emacs-lsp-booster` and by extension `eglot-booster` act as men-in-the-middle and thus I do not expect this kind of info displayed as they were coming from the error stream of the language server.

However I do not know the internals of the system, so it may as well be completely normal.

**Comment by jdtsmith** [comment]
The server eglot is interacting with _is_ in fact `emacs-lsp-booster`, which runs and interfaces with the underlying server, so anything it puts on stderr (including a notification about what it's doing) gets mentioned.  I like it because it's an easy way to confirm things are working as expected!

**Comment by maxecharel** [comment]
> The server eglot is interacting with _is_ in fact `emacs-lsp-booster`, which runs and interfaces with the underlying "real" server, so anything it puts on stderr (including a notification about what it's doing) gets mentioned. I like it because it's an easy way to confirm things are working as expected!

Thanks for the explanation. Nice, it means that everything works fine! Thank you again for the implementation :) Cheers!
