### ISSUE TITLE
Is Java jdtls supported?

### ISSUE THREAD

**Issue by uqix** [jdtsmith/eglot-booster#3]
https://github.com/eclipse-jdtls/eclipse.jdt.ls?tab=readme-ov-file#managing-connection-types

> To use standard streams(stdin, stdout) of the server process do not set any of the above environment variables and the server will fall back to standard streams.

Is this relevant?

**Comment by uqix** [comment]
https://github.com/jdtsmith/eglot-booster/blob/6fa5f04a70ecf40e942f647deaaf70ddd5f6d864/eglot-booster.el#L52

Here's the problem: my java elgot config contains `:initializationOptions`:

```elisp

(add-to-list
 'eglot-server-programs
 '(java-ts-mode
   .
   ("jdtls"
    "--jvm-arg=-javaagent:/opt/lombok.jar"
    "--jvm-arg=-Xmx4G"
    "--jvm-arg=-XX:+UseStringDeduplication"
    :initializationOptions (:extendedClientCapabilities (:classFileContentsSupport t)))))

```
so it's not wrapped.

**Comment by jdtsmith** [comment]
I don't recall why I outlawed those.  Can you try the `allow-initialization-options` branch and let me know how it works?

**Comment by uqix** [comment]
> I don't recall why I outlawed those. Can you try the `allow-initialization-options` branch and let me know how it works?

It works now, thanks.

**Comment by jdtsmith** [comment]
Thanks merged.
