### ISSUE TITLE
Dose Not Ignore Docker Connections

### ISSUE THREAD

**Issue by nehrbash** [jdtsmith/eglot-booster#7]
Apparently a docker tramp connection is not considered a remote file which causes obvious issues when lsp-booster is not installed in the container.

**Comment by jdtsmith** [comment]
Like a local docker?  I don't see why that'd be different from any other local connection.  Can you run a system-wide wrapper executable that invokes a mounted docker program?  This is with `eglot-booster-no-remote-boost` enabled?

**Comment by nehrbash** [comment]
yes a local docker container. sorry I completely misread eglot-booster-no-reomte-boost. I thought it was a internal variable that was dynamically set, not a defcustom. when set to non-nil it dose not boost as expected. In my case it wasn't working because I copied the binary into place and the container has the wrong version of libc. `file-remote-p` returns `"/docker:dev-container:"`. I guess I'm too accustomed to static binaries at this point 😅.
