### ISSUE TITLE
Warning: ‘buffer-local-value’ is an obsolete generalized variable.

### ISSUE THREAD

**Issue by claytharrison** [jdtsmith/eglot-booster#8]
The first time I start eglot after opening Emacs I get this warning -

```
~/.config/emacs/.local/straight/build-29.1/eglot-booster/eglot-booster.el:
    Warning: ‘buffer-local-value’ is an obsolete generalized variable.
```

I'm on Emacs 29.1, using the latest Doom Emacs. Is there anything I can do to fix or suppress this?

**Comment by jdtsmith** [comment]
Thanks, had missed that obsoletion.  Just uploaded a fix, give this a try.
